// CASEVAULT Clean Seeds
// NOTE: INITIAL_USERS remains 0 seed demo accounts as requested. Real registered officers handle cases.
export const INITIAL_USERS = [];

export const INITIAL_CASES = [
  {
    id: 'CASE-1024',
    firNumber: 'FIR-2026-1024',
    title: 'State vs. Cyber Fraud Syndicate (Banking Phishing)',
    caseType: 'Cyber Crime',
    status: 'Investigation',
    priority: 'High',
    policeStation: 'Cyber Crime Police Station',
    investigatingOfficer: 'SI Shivam Kumar Singh',
    dateOpened: '2026-01-14',
    incidentDate: '2026-01-10',
    location: 'Sevoke Road Commercial Hub, Siliguri',
    complainant: 'Subhasish Roy (HDFC Bank Account Holder)',
    accused: 'Unknown Phishing Network (IP Node #192.168.4.12)',
    sections: 'IPC Sec 420, IT Act Sec 66C/66D',
    summary: 'Investigation into unauthorized digital wire transfers amounting to ₹4,50,000 via cloned payment gateway. Server IP logs and SSL certificates secured.',
    documentsCount: 2,
    hashChainVerified: true
  },
  {
    id: 'CASE-1025',
    firNumber: 'FIR-2026-1025',
    title: 'Armed Heist at City Gold Refinery Depot',
    caseType: 'Robbery & Dacoity',
    status: 'Active',
    priority: 'Critical',
    policeStation: 'Siliguri Police Station',
    investigatingOfficer: 'Insp. Karan Kumar',
    dateOpened: '2026-02-02',
    incidentDate: '2026-02-01',
    location: 'Hill Cart Road, Ward 11, Siliguri',
    complainant: 'Ramesh Verma (Refinery Owner)',
    accused: 'Bikram Mallick & 3 accomplices',
    sections: 'IPC Sec 392, Sec 397, Arms Act Sec 25',
    summary: 'Armed robbery of 1.8 kg gold bullion from city refinery depot. High-definition CCTV footage seized and bullet casings sent for ballistic analysis.',
    documentsCount: 2,
    hashChainVerified: true
  },
  {
    id: 'CASE-1026',
    firNumber: 'FIR-2026-1026',
    title: 'Inter-State Commercial Contraband Transit Raid',
    caseType: 'NDPS Act',
    status: 'Under Review',
    priority: 'High',
    policeStation: 'Matigara Police Station',
    investigatingOfficer: 'SI Somesh Mandal',
    dateOpened: '2026-02-18',
    incidentDate: '2026-02-17',
    location: 'Matigara Checkpost (NH-31 Highway)',
    complainant: 'Sub-Inspector T. K. Roy',
    accused: 'Sunil Chettri & Md. Arif',
    sections: 'NDPS Act Sec 21(c), Sec 29',
    summary: 'Highway intercept and seizure of 450 grams of commercial grade contraband concealed inside heavy goods transport vehicle. Chemical analysis report pending SFSL clearance.',
    documentsCount: 1,
    hashChainVerified: true
  },
  {
    id: 'CASE-1027',
    firNumber: 'FIR-2026-1027',
    title: 'Counterfeit Land Deed & Forgery Racket',
    caseType: 'Land Fraud',
    status: 'Court Trial',
    priority: 'Medium',
    policeStation: 'Pradhannagar Police Station',
    investigatingOfficer: 'SI Shivam Kumar Singh',
    dateOpened: '2026-03-05',
    incidentDate: '2026-01-12',
    location: 'Champasari Extension, Siliguri',
    complainant: 'Deepak Agarwal',
    accused: 'Suresh Chandra Pal & Registry Clerk',
    sections: 'IPC Sec 465, Sec 468, Sec 471, Sec 120B',
    summary: 'Fabrication of counterfeit government stamps and illegal registration of municipal land plot. Forensic handwriting verification report attached to chargesheet.',
    documentsCount: 1,
    hashChainVerified: true
  },
  {
    id: 'CASE-1028',
    firNumber: 'FIR-2026-1028',
    title: 'Fake Indian Currency Note (FICN) Seizure',
    caseType: 'Counterfeit Currency',
    status: 'Active',
    priority: 'Critical',
    policeStation: 'Bagdogra Police Station',
    investigatingOfficer: 'Insp. Karan Kumar',
    dateOpened: '2026-03-22',
    incidentDate: '2026-03-21',
    location: 'Bagdogra Airport Junction',
    complainant: 'Air Intelligence Unit / Custom Officer S. Roy',
    accused: 'Karan Thapa',
    sections: 'IPC Sec 489A, Sec 489B, Sec 489C',
    summary: 'Seizure of ₹1,200,000 face-value counterfeit currency notes near airport transit route. Serial numbers cross-verified with RBI security standards.',
    documentsCount: 1,
    hashChainVerified: true
  },
  {
    id: 'CASE-1029',
    firNumber: 'FIR-2026-1029',
    title: 'Tea Estate Perimeter Homicide Investigation',
    caseType: 'Homicide',
    status: 'Investigation',
    priority: 'High',
    policeStation: 'SIT Police Station',
    investigatingOfficer: 'SI Somesh Mandal',
    dateOpened: '2026-04-10',
    incidentDate: '2026-04-09',
    location: 'Dagapur Tea Estate Sector 4',
    complainant: 'Estate Manager Manoranjan Ghosh',
    accused: 'Under Investigation',
    sections: 'IPC Sec 302, Sec 201',
    summary: 'Unidentified body recovered near estate canal. Inquest report prepared under CrPC Sec 174. Post-mortem report logged under cryptographic chain of custody.',
    documentsCount: 1,
    hashChainVerified: true
  }
];

export const INITIAL_DOCUMENTS = [
  {
    id: 'DOC-1024-01',
    caseId: 'CASE-1024',
    name: 'FIR_Copy_Cyber_Fraud_1024.pdf',
    docType: 'FIR',
    docTypeLabel: 'First Information Report (FIR)',
    version: 1,
    uploadedBy: 'SI Shivam Kumar Singh',
    uploadedByRole: 'Investigating Officer',
    uploadDate: '2026-01-14',
    uploadTime: '10:30 AM',
    classification: 'Confidential',
    status: 'Verified',
    sha256: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
    lastVerified: '2026-01-14 10:30 AM',
    fileSize: '420 KB',
    pageCount: 3,
    description: 'Original FIR registered under IT Act Sec 66D for unauthorized digital banking transaction.',
    content: 'POLICE DEPARTMENT - CYBER CRIME STATION\nFIRST INFORMATION REPORT\nFIR No: FIR-2026-1024\nDate: 14 Jan 2026\nComplainant: Subhasish Roy\nDetails: Unauthorized withdrawal of funds via fraudulent phishing portal.'
  },
  {
    id: 'DOC-1024-02',
    caseId: 'CASE-1024',
    name: 'IP_Trace_Log_Analysis.pdf',
    docType: 'Forensic Report',
    docTypeLabel: 'Forensic & Laboratory Report',
    version: 1,
    uploadedBy: 'SI Shivam Kumar Singh',
    uploadedByRole: 'Investigating Officer',
    uploadDate: '2026-01-16',
    uploadTime: '02:15 PM',
    classification: 'Restricted',
    status: 'Verified',
    sha256: 'b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef01',
    lastVerified: '2026-01-16 02:15 PM',
    fileSize: '1.2 MB',
    pageCount: 7,
    description: 'Server IP log trace and VPN exit node identification report.',
    content: 'DIGITAL FORENSICS LAB - CYBER CELL\nTECHNICAL ANALYSIS REPORT\nTarget IP: 192.168.4.12\nISP: National Telecom Infra\nVPN Routing Traced to regional node.'
  },
  {
    id: 'DOC-1025-01',
    caseId: 'CASE-1025',
    name: 'FIR_Copy_Gold_Refinery_Heist.pdf',
    docType: 'FIR',
    docTypeLabel: 'First Information Report (FIR)',
    version: 1,
    uploadedBy: 'Insp. Karan Kumar',
    uploadedByRole: 'Station House Officer',
    uploadDate: '2026-02-02',
    uploadTime: '09:00 AM',
    classification: 'Confidential',
    status: 'Verified',
    sha256: 'c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef012',
    lastVerified: '2026-02-02 09:00 AM',
    fileSize: '512 KB',
    pageCount: 4,
    description: 'Initial police report for armed robbery at City Gold Refinery Depot.',
    content: 'SILIGURI POLICE STATION - FIR-2026-1025\nArmed dacoity at Hill Cart Road bullion depot.\nStolen property: 1.8 kg gold bullion bars.'
  },
  {
    id: 'DOC-1025-02',
    caseId: 'CASE-1025',
    name: 'Seizure_Memo_Ballistic_Evidence.pdf',
    docType: 'Evidence Record',
    docTypeLabel: 'Seizure Memo & Evidence Record',
    version: 1,
    uploadedBy: 'Insp. Karan Kumar',
    uploadedByRole: 'Station House Officer',
    uploadDate: '2026-02-03',
    uploadTime: '11:45 AM',
    classification: 'Confidential',
    status: 'Verified',
    sha256: 'd4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0123',
    lastVerified: '2026-02-03 11:45 AM',
    fileSize: '680 KB',
    pageCount: 2,
    description: 'Seizure memo of 7.65mm fired cartridge case recovered from scene.',
    content: 'SEIZURE MEMO - IPC SEC 102 CrPC\nRecovered: 1x Fired Cartridge Case (7.65mm)\nLocation: Floor of Refinery Vault B.'
  },
  {
    id: 'DOC-1026-01',
    caseId: 'CASE-1026',
    name: 'Seizure_Memo_NDPS_Contraband.pdf',
    docType: 'Evidence Record',
    docTypeLabel: 'Seizure Memo & Evidence Record',
    version: 1,
    uploadedBy: 'SI Somesh Mandal',
    uploadedByRole: 'Investigating Officer',
    uploadDate: '2026-02-18',
    uploadTime: '04:30 PM',
    classification: 'Restricted',
    status: 'Verified',
    sha256: 'e5f67890123456789abcdef0123456789abcdef0123456789abcdef01234',
    lastVerified: '2026-02-18 04:30 PM',
    fileSize: '390 KB',
    pageCount: 3,
    description: 'NDPS Act commercial quantity contraband seizure report.',
    content: 'MATIGARA POLICE STATION - NDPS SEIZURE MEMO\nQuantity: 450 grams contraband.\nVehicle: WB-74-AX-9912 Goods Carrier.'
  },
  {
    id: 'DOC-1027-01',
    caseId: 'CASE-1027',
    name: 'Forged_Land_Deed_Forensic_Verification.pdf',
    docType: 'Forensic Report',
    docTypeLabel: 'Forensic & Laboratory Report',
    version: 1,
    uploadedBy: 'SI Shivam Kumar Singh',
    uploadedByRole: 'Investigating Officer',
    uploadDate: '2026-03-08',
    uploadTime: '11:00 AM',
    classification: 'Confidential',
    status: 'Verified',
    sha256: 'f67890123456789abcdef0123456789abcdef0123456789abcdef012345',
    lastVerified: '2026-03-08 11:00 AM',
    fileSize: '850 KB',
    pageCount: 5,
    description: 'Questioned Document Examiner (QDE) handwriting and seal analysis.',
    content: 'STATE FORENSIC SCIENCE LABORATORY\nHANDWRITING & SEAL EXAMINATION REPORT\nDeed No: 4412/2025\nConclusion: Stamp impression is counterfeit.'
  },
  {
    id: 'DOC-1028-01',
    caseId: 'CASE-1028',
    name: 'FICN_Seizure_Serial_Analysis.pdf',
    docType: 'Evidence Record',
    docTypeLabel: 'Seizure Memo & Evidence Record',
    version: 1,
    uploadedBy: 'Insp. Karan Kumar',
    uploadedByRole: 'Investigating Officer',
    uploadDate: '2026-03-23',
    uploadTime: '01:20 PM',
    classification: 'Confidential',
    status: 'Verified',
    sha256: '7890123456789abcdef0123456789abcdef0123456789abcdef01234567a',
    lastVerified: '2026-03-23 01:20 PM',
    fileSize: '460 KB',
    pageCount: 2,
    description: 'Fake Indian Currency Note serial number log and UV watermark test report.',
    content: 'BAGDOGRA POLICE STATION - FICN SEIZURE MEMO\nSeized: ₹1,200,000 in fake notes.'
  },
  {
    id: 'DOC-1029-01',
    caseId: 'CASE-1029',
    name: 'Inquest_Report_Tea_Estate.pdf',
    docType: 'Investigation Report',
    docTypeLabel: 'Investigation Progress Diary',
    version: 1,
    uploadedBy: 'SI Somesh Mandal',
    uploadedByRole: 'Investigating Officer',
    uploadDate: '2026-04-10',
    uploadTime: '05:40 PM',
    classification: 'Restricted',
    status: 'Verified',
    sha256: '890123456789abcdef0123456789abcdef0123456789abcdef01234567ab',
    lastVerified: '2026-04-10 05:40 PM',
    fileSize: '610 KB',
    pageCount: 4,
    description: 'Inquest report prepared under Sec 174 CrPC at scene of crime.',
    content: 'SIT POLICE STATION - CRIME SCENE INQUEST REPORT\nLocation: Dagapur Tea Estate Sector 4.'
  }
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'LOG-001',
    timestamp: '2026-01-14 10:30 AM',
    user: 'SI Shivam Kumar Singh',
    userRole: 'Investigating Officer',
    policeStation: 'Cyber Crime Police Station',
    action: 'Case Created',
    actionBadge: 'create',
    caseId: 'CASE-1024',
    documentId: null,
    documentName: null,
    details: 'Registered new Cyber Crime case CASE-1024 (FIR-2026-1024).',
    hash: '8f9e0a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789ab',
    ipAddress: '10.14.22.105'
  },
  {
    id: 'LOG-002',
    timestamp: '2026-02-02 09:00 AM',
    user: 'Insp. Karan Kumar',
    userRole: 'Station House Officer',
    policeStation: 'Siliguri Police Station',
    action: 'Case Created',
    actionBadge: 'create',
    caseId: 'CASE-1025',
    documentId: null,
    documentName: null,
    details: 'Registered armed heist case CASE-1025 (FIR-2026-1025).',
    hash: '9a0b1c2d3e4f567890123456789abcdef0123456789abcdef0123456789abc',
    ipAddress: '10.14.18.44'
  }
];

export const POLICE_STATIONS = [
  'Siliguri Police Station',
  'Matigara Police Station',
  'Bagdogra Police Station',
  'Pradhannagar Police Station',
  'Pradhan Nagar Police Station',
  'Cyber Crime Police Station',
  'SIT Police Station'
];

export const DOCUMENT_TYPES = [
  { value: 'FIR', label: 'First Information Report (FIR)' },
  { value: 'Investigation Report', label: 'Investigation Progress Diary' },
  { value: 'Witness Statement', label: 'Witness Statement (Sec 161 CrPC)' },
  { value: 'Evidence Record', label: 'Seizure Memo & Evidence Record' },
  { value: 'Forensic Report', label: 'Forensic & Laboratory Report' },
  { value: 'Charge Sheet', label: 'Final Police Report / Charge Sheet' },
  { value: 'Court Filing', label: 'Court Order & Legal Notice' }
];

